# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.3
_src_path: https://github.com/osgeosuomi/qgis-plugin-copier-template.git
add_github_workflows: true
insert_copyright_header: true
is_monorepo_component: false
min_code_coverage: 80
plugin_metadata_author: Joonalai
plugin_metadata_email: dev@cofactor.fi
plugin_metadata_repository_url: https://github.com/Joonalai/profiler-qgis-plugin
qgis_plugin_about: This plugin extends the Debugging/Development Tools dock widget
    profiling panel in various ways to allow advanced profiling of QGIS and plugins.
qgis_plugin_class: ProfilerPlugin
qgis_plugin_description: Tool and library to make profiling QGIS and plugins easy
qgis_plugin_module: profiler_plugin
qgis_plugin_name: Profiler
qgis_version: QGIS3 & QGIS4
setup_translations: false
