[project]
name = "profiler-qgis-plugin"
version = "0.1.0.post1"
description = "The QGIS Profiler Plugin aims to extend QGIS Profiler development tool to be able to profile plugins and QGIS itself easily."
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = ["qgis_plugin_tools>=2.0.0", "profiler-qgis-core"]

[project.urls]
homepage = "https://profiler-qgis-plugin.readthedocs.io"
repository = "https://github.com/Joonalai/profiler-qgis-plugin"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "profiler_plugin"
include = ["**/py.typed", "**/metadata.txt", "**/*.svg", "**/*.ts", "**/*.ui"]


[tool.uv.sources]
profiler-qgis-core = { workspace = true }

[tool.qgis_plugin_dev_tools]
plugin_package_name = "profiler_plugin"
version_number_source = "pyproject"
changelog_file_path = "../../CHANGELOG.md"
env_file_path = "../../.env"
runtime_requires = [
  "qgis_plugin_tools",
  "profiler-qgis-plugin",
  "profiler-qgis-core",
]

[project.entry-points.qgis_plugin_dev_tools]
profiler_plugin = "profiler_plugin"
