name: Create draft release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version number without "v" tag prefix (i.e. "1.0.0")

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Inspect the draft release and make sure it is correct before publishing
      - name: Create a draft release into Github releases
        uses: nlsfi/python-repo-draft-release-action@d2e2bfad49de0aca3dffe1a057f04508696c0b7a # v1.1.0
        with:
          version: ${{ inputs.version }}
          version_file: |
            components/core/pyproject.toml
            components/plugin/pyproject.toml
