# Inspired by https://github.com/nlsfi/segment-reshape-qgis-plugin/blob/main/.github/workflows/release.yml

name: Release

on:
  release:
    types: [released]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          pip install -q -U uv
      - run: |
          uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - uses: svenstaro/upload-release-action@2.9.0
        with:
          file: dist/*
          file_glob: true

  qgis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      # use extra pip install . to do a non-editable install,
      # so that .dist-info will go the package instead of .egg-info
      - run: |
          pip install uv
          uv sync
          uv pip install . --no-deps
      - run: |
          qgis-plugin-dev-tools build
      - run: |
          qgis-plugin-dev-tools publish dist/*.zip
        env:
          QPDT_PUBLISH_USERNAME: ${{ secrets.QGIS_REPO_USERNAME }}
          QPDT_PUBLISH_PASSWORD: ${{ secrets.QGIS_REPO_PASSWORD }}
      - uses: svenstaro/upload-release-action@2.9.0
        with:
          file: dist/*
          file_glob: true
