name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        qgis-image-tags: [release-3_34, "3.40", latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: |
          apt update
          apt install -y python3-venv curl
      - run: |
          python3 -m venv --system-site-packages .venv
      - run: |
          .venv/bin/pip3 install -q -U pip
          .venv/bin/pip3 install -q -r requirements.txt --no-deps --only-binary=:all:
          .venv/bin/pip3 install . --no-deps
      - run: |
          .venv/bin/pytest --qgis_disable_gui --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.qgis-image-tags == 'latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Joonalai/profiler-qgis-plugin
          fail_ci_if_error: true
