name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        qgis-image-tags: ["3.40-noble", "3.44-noble", "latest"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install venv
        run: |
          apt update
          apt install -y python3-venv curl
      - name: Create virtualenv and install dependencies
        run: |
          python3 -m venv --system-site-packages .venv
          .venv/bin/pip3 install -q -U uv
          .venv/bin/uv sync --all-packages --all-groups --locked --active

      - name: Run tests
        run: |
          .venv/bin/uv run pytest -v --qgis_disable_gui --cov --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.qgis-image-tags == 'latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Joonalai/profiler-qgis-plugin
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && matrix.qgis-image-tags == 'latest' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
