name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        qgis-image-tags: ["3.40-noble", "3.44-noble", "4.0-questing", "latest"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

      - name: Install venv
        run: |
          uv venv --system-site-packages

      - name: Run tests
        run: |
          uv sync --all-packages --all-groups --locked --active
          uv run pytest -v --qgis_disable_gui --cov --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy


      - name: Install curl
        if: ${{ matrix.qgis-image-tags == 'latest' }}
        run: |
          apt update
          apt install -y curl

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.qgis-image-tags == 'latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Joonalai/profiler-qgis-plugin
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && matrix.qgis-image-tags == 'latest' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
